{% set name = "fitsnap3" %}
{% set version = "3.1.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fitsnap3-{{ version }}.tar.gz
  sha256: 505ae147de9113241a560c3afee181131d0a9b5dc342a2c4d6b0edf06caa98e3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.10
  run:
    - numpy >=1.17.2
    - pandas >=0.25.1
    - psutil >=5.6.3
    - python >=3.10
    - scipy >=1.3.1
    - lammps
    - mpi4py
    - cython
    - pyyaml
    - scikit-learn
    - sympy
    - tabulate
    - pytorch
    - virtualenv

test:
  imports: 
    - fitsnap3lib
  commands:
    - export OMPI_MCA_plm=isolated
    - export OMPI_MCA_rmaps_base_oversubscribe=yes
    - export OMPI_MCA_btl_vader_single_copy_mechanism=none
    - # python -m fitsnap3 -h .
    - pip check
  requires:
    - pip

about:
  home: https://github.com/FitSNAP/FitSNAP
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Software for generating SNAP machine-learning interatomic potentials
  description: |
    A Python Package For Training SNAP Interatomic Potentials for use in
    the LAMMPS molecular dynamics package
  doc_url: https://github.com/FitSNAP/FitSNAP
  dev_url: https://github.com/FitSNAP/FitSNAP

extra:
  recipe-maintainers:
    - rohskopf
    - jan-janssen
